api/urls.py
from django.conf.urls import url
from rest_framework import routers
from api import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'save-password', views.SavePasswordViewSet, base_name="save-password")  # NOQA
urlpatterns = [
    url(r'^show-download/', views.ShowDownloadView.as_view(), name="show-download-list"),  # NOQA
    url(r'^upload-file/', views.FileUploadView.as_view(), name="upload-file"),
    url(r'^signup/', views.SignUpUserView.as_view(), name="signup"),
    url(r'^login/', views.LoginView.as_view(), name="login"),
    url(r'^logout/', views.LogoutView.as_view(), name="logout"),

]
urlpatterns += router.urls

authuser/urls.py
from django.conf.urls import url
from authuser import views

app_name = 'auth'

urlpatterns = [
    url(r'^signup/$', views.SignUpView.as_view(), name="signup"),
    url(r'^login/$', views.LogInView.as_view(), name="login")
]

icanupload/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import (url, include)
from django.conf.urls.static import static
from django.conf import settings
from api import urls

urlpatterns = [
    path('godmode/', admin.site.urls),
    url(r'^', include('dashboard.urls'), name='dashboard'),
    url(r'auth/', include('authuser.urls'), name='auth'),
    url(r'api/v1/', include(urls), name='api')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authuser/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.core.exceptions import ValidationError


class IcanuploadUserManager(BaseUserManager):
    """
    custom user manager for Icanupload user
    this user manager is responsible for all
    CRUD operation over custom user models
    """

    def create_user(self, username=None, email=None, password=None):
        if not username or username is None:
            raise ValidationError("User must have username")
        if not email or email is None:
            raise ValidationError("User must have email address")
        user = self.model(
            username=username,
            email=self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username=username,
                                email=email,
                                password=password)
        user.is_admin = True
        # user.is_staff = True
        user.save(using=self._db)
        return user


class IcanuploadUser(AbstractBaseUser):
    """
    parent class for all users in icanuplaod application
    """
    email = models.EmailField(max_length=255, unique=True, db_index=True)
    username = models.CharField(max_length=255, unique=True, db_index=True)
    # Personal Information
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    profile_image = models.FileField(upload_to='authuser/profile', null=True, blank=True)  # NOQA
    # Permissions
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    # Verification
    is_email_varified = models.BooleanField(default=False)
    # Other
    created = models.DateTimeField(auto_now_add=True)  # Automatically set the field to now when the object is first created.  # NOQA
    updated = models.DateTimeField(auto_now=True)  # Automatically set the field to now every time the object is saved.  # NOQA
    objects = IcanuploadUserManager()
    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email']

    # def __str__(self):
    #     return self.get_full_name

    def get_short_name(self):
        if self.first_name:
            return self.first_name
        else:
            return self.email

    def get_full_name(self):
        if self.first_name and self.last_name:
            return "%s %s" % (self.first_name, self.last_name)
        else:
            return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def display_name(self):
        if self.first_name:
            return self.first_name
        else:
            return self.email

authuser/views.py
from django.shortcuts import render  # NOQA
from django.views import View


class SignUpView(View):

    def get(self, request):
        return render(request, 'authuser/signup.html')


class LogInView(View):

    def get(self, request):
        return render(request, 'authuser/login.html')

templates/authuser/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="msvalidate.01" content="B34B4191E0BDA0C769D024E1913BF843"/><!--for Bling-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ICanUpload - No matter where you go – take your files with you</title>
    <link rel="shortcut icon" href="{% static 'Images/icu_icon.png' %}"/>  <!--Title Img-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>
    <!--ajax-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!--jquery-confirm-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <!--Added to get csrf token from cookie-->
    <!-- code to get token = $.cookie("csrftoken") -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <!--Progress-bar-->
    <script src="{% static 'loading-bar/loading-bar.js' %}"></script>
    <script src="{% static 'loading-bar/loading-bar.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'loading-bar/loading-bar.css' %}">
    <!--fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!--Custom_CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom_css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom_css/font.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom_css/button.css' %}">
    <!--Custom_JS-->
    <script src="{% static 'js/custom_js/authuser/signup.js' %}"></script>
</head>

<body>

<div class="container" style="padding-top: 8%;padding-bottom: 5%;">

    {% block content %}

    {% endblock %}

</div>

<script>
    var SIGNUP_USER_URL = "{% url 'api:signup' %}"
    var LOGIN_URL = "{% url 'api:login' %}"
    var LOGOUT_URL = "{% url 'api:logout' %}"
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous">
</script>

<!--Custom_JS-->


{% block extra_js %}
{% endblock %}

{% block extra_css %}
<style>
html {
    background: linear-gradient( rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.7) ), url(../../static/images/background.jpg) no-repeat center fixed;
}
</style>
{% endblock %}

</body>

</html>

templates/authuser/login.html
{% extends 'authuser/base.html' %}
{% load static %}
{% block content %}
    <style>

    </style>
    <div class="container center">
        <center>
            <a class="navbar-brand" href="/">
                <img src="{% static 'images/logo.png' %}" style="width: 150px;"
                     class="d-inline-block align-top" alt="icanupload.com">
            </a>
        </center>
        <form id="login-form">
            {% csrf_token %}
            <div class="form-group" style="margin-top: 2rem;">
                <input type="text" class="form-control" id="username" name="username" placeholder="Username, Email"
                       autocomplete="off">
                <input type="password" class="form-control" id="password" name="password" placeholder="Password"
                       autocomplete="off" style="margin-top: 1rem">
            </div>
            <p id="error-msg"></p>
            <button type="submit" style="width: 100%;" class="btn btn-primary">Log In</button>
        </form>
        <div class="login-signup" style="margin-top: 1rem">
            Don't have an account? <a href="{% url 'auth:signup' %}">Sign up</a>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/custom_js/authuser/login.js' %}"></script>
{% endblock %}

templates/authuser/nav.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light">
    <a class="navbar-brand" href="/">
        <img src="{% static 'Images/logo.png' %}" style="width: 200px;padding-top: 10px"
             class="d-inline-block align-top" alt="">
    </a>
</nav>

templates/authuser/signup.html
{% extends 'authuser/base.html' %}
{% load static %}
{% block content %}
    <div class="container center" style="min-width: 30%">
        <a class="navbar-brand" href="/">
            <img src="{% static 'images/logo.png' %}" style="width: 150px;"
                 class="d-inline-block align-top" alt="icanupload.com">
        </a>
        <h1>Create your account</h1>
        <p>Already have an account? <a href="{% url 'auth:login' %}">Log In</a></p>
        <form method="post" id="siginup-form">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="firstname">First name</label>
                    <input type="text" name="first_name" class="form-control" id="firstname" placeholder="First name"
                           autocomplete="off">
                </div>
                <div class="form-group col-md-6">
                    <label for="lastname">Last name</label>
                    <input type="text" class="form-control" name="last_name" id="lastname" placeholder="Last name"
                           autocomplete="off">
                </div>
            </div>
            <div class="form-group">
                <label for="username">User name</label>
                <input type="text" class="form-control" id="username" name="username" placeholder="User name"
                       autocomplete="off">
            </div>
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email" autocomplete="off">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Password"
                           autocomplete="off">
                </div>
                <div class="form-group col-md-6">
                    <label for="conform">confirm</label>
                    <input type="password" class="form-control" name="confirm" id="confirm" placeholder="confirm"
                           autocomplete="off">
                </div>
            </div>
            <p id="error-msg"></p>
            <button type="submit" class="btn btn-primary">Sign Me Up</button>
        </form>
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/custom_js/authuser/signup.js' %}"></script>
{% endblock %}