api/urls.py
from django.conf.urls import url
from rest_framework import routers
from api import views

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'save-password', views.SavePasswordViewSet, base_name="save-password")  # NOQA
urlpatterns = [
    url(r'^show-download/', views.ShowDownloadView.as_view(), name="show-download-list"),  # NOQA
    url(r'^upload-file/', views.FileUploadView.as_view(), name="upload-file"),
    url(r'^signup/', views.SignUpUserView.as_view(), name="signup"),
    url(r'^login/', views.LoginView.as_view(), name="login"),
    url(r'^logout/', views.LogoutView.as_view(), name="logout"),

]
urlpatterns += router.urls

dashboard/urls.py
from django.conf.urls import url
from django.urls import path
from dashboard import views
urlpatterns = [
    path('', views.DashboardView.as_view(), name="index"),
    url(r'^home/$', views.DashboardView.as_view(), name="home")
]

icanupload/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import (url, include)
from django.conf.urls.static import static
from django.conf import settings
from api import urls

urlpatterns = [
    path('godmode/', admin.site.urls),
    url(r'^', include('dashboard.urls'), name='dashboard'),
    url(r'auth/', include('authuser.urls'), name='auth'),
    url(r'api/v1/', include(urls), name='api')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse  # NOQA
from django.views import View
from uploader.models import FileData


class DashboardView(View):

    def get(self, request):
        if request.user.is_authenticated:
            return render(request, 'dashboard/dashboard/dashboard.html')
        else:
            token_id = request.GET.get('s', '')
            if token_id:
                try:
                    file = FileData.objects.get(token=token_id)
                    if file.password:
                        context = {
                            'data': file.password,
                            'key': token_id
                        }
                    else:
                        context = {
                            'data': 'Download',
                            'key': token_id
                        }
                except FileData.DoesNotExist:
                    context = {
                        'data': "Wrong",
                        'key': token_id
                    }
                return render(request, 'dashboard/index/index.html', context)
            else:
                return render(request, 'dashboard/index/index.html')

templates/dashboard/index/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="msvalidate.01" content="B34B4191E0BDA0C769D024E1913BF843"/><!--for Bling-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ICanUpload - No matter where you go – take your files with you</title>
    <link rel="shortcut icon" href="{% static 'Images/icu_icon.png' %}"/>  <!--Title Img-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.js"></script>
    <script src="http://malsup.github.com/jquery.form.js"></script>
    <!--ajax-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!--jquery-confirm-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <!--Added to get csrf token from cookie-->
    <!-- code to get token = $.cookie("csrftoken") -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
    <!--Progress-bar-->
    <script src="{% static 'loading-bar/loading-bar.js' %}"></script>
    <script src="{% static 'loading-bar/loading-bar.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'loading-bar/loading-bar.css' %}">
    <!--fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <!--Custom_CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom_css/base.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom_css/button.css' %}">


</head>

<body>

<div class="container">

    {% include 'dashboard/index/nav.html' %}

    {% block content %}

    {% endblock %}

</div>

<script>
    var SHOW_DOWNLOAD_LIST_URL = "{% url 'api:show-download-list' %}"
    var SAVE_PASSWORD_URL = "{% url 'api:save-password-list' %}"
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous">
</script>

<!--Custom_JS-->


{% block extra_js %}

{% endblock %}

{% block extra_css %}

{% endblock %}
</body>

</html>

templates/dashboard/index/index.html
<!--
This Page open only if user is NOT Log In
-->
{% extends 'dashboard/index/base.html' %}
{% load static %}
{% block content %}
    <div class="row" id="upload_outer_div">
        <div class="col-md-12" style="text-align: center;">
            <h2 class="tagline">No matter where you go – <br>take your files with you</h2>
            <form action="{% url 'api:upload-file' %}" method="post" id="form_upload" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="button" id="upload_btn">Upload</div>
                <input type="file" name="file" id="getFile" autocomplete=off
                       multiple/>
                <input type="hidden" id="Hiddate" name="csrfmiddlewaretoken" value="{% csrf_token %}"/>
                <button type="submit">submit</button>
            </form>
            <div id="progressBar"
                 style="width:100%;height:60px;margin-top: 20px;"
                 data-preset="rainbow">
            </div>
        </div>
    </div>
    {% if data %}
        <script>
            $(document).ready(function () {
                {% if data == "Wrong" %}
                    $.dialog({
                        backgroundDismiss: false,
                        boxWidth: '300px',
                        icon: 'fas fa-ghost',
                        useBootstrap: false,
                        animation: 'top',
                        title: 'Not Found',
                        content: '' +
                        '<div class="form-group" style="padding-top: 10px;text-align: center;">' +
                        '<b>Key not found</b>' +
                        '</div>',
                    });
                {% else %}
                    {% if data == "Download"%}
                        downloadModel({{ key }});
                    {% else %}
                        $.confirm({
                            backgroundDismiss: false,
                            boxWidth: '300px',
                            icon: 'fas fa-key',
                            useBootstrap: false,
                            animation: 'top',
                            title: 'Password',
                            content: '' +
                            '<form action="" class="formName">' +
                            '<div class="form-group">' +
                            // '<label>enter password</label>' +
                            '<input type="password" placeholder="enter password" class="password form-control" style="margin-top:10px" required />' +
                            '</div>' +
                            '</form>',
                            buttons: {
                                formSubmit: {
                                    text: 'Submit',
                                    btnClass: 'btn btn-primary btn-lg',
                                    action: function () {
                                        var password = this.$content.find('.password').val();
                                        if (!password) {
                                            $.alert('provide a valid password');
                                            return false;
                                        } else {
                                            downloadModel({{ key }}, password);
                                        }
                                    }
                                },
                                close: {
                                    text: 'Close',

                                    action: function () {
                                        window.location.href = '/';
                                    }
                                },
                            },
                        });

                    {% endif %}
                {% endif %}
            });
        </script>
    {% endif %}
{% endblock %}
{% block extra_js %}
    <script src="{% static 'js/custom_js/dashboard/index/base.js' %}"></script>
    <script src="{% static 'js/custom_js/dashboard/index/download.js' %}"></script>
{% endblock %}

templates/dashboard/index/nav.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-light">
    <a class="navbar-brand" href="/">
        <img src="{% static 'images/logo.png' %}" style="width: 200px;padding-top: 10px"
             class="d-inline-block align-top" alt="icanupload.com">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto"></ul>
        <a class="nav-link" href="/auth/login">LOG IN</a>
        <a class="nav-link" href="/auth/signup">SIGN UP</a>
        <form method="get" class="form-inline" id="search_form">
            <input class="form-control mr-sm-2" type="search" id="search_key" placeholder="enter key"
                   aria-label="Search" value="{{ key }}" autocomplete="off">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>